[2020-07-14 02:26:31 +0000] [4592] [INFO] Starting gunicorn 20.0.4
[2020-07-14 02:26:31 +0000] [4592] [INFO] Listening at: http://0.0.0.0:8000 (4592)
[2020-07-14 02:26:31 +0000] [4592] [INFO] Using worker: sync
[2020-07-14 02:26:31 +0000] [4595] [INFO] Booting worker with pid: 4595
[2020-07-14 02:26:31 +0000] [4595] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2020-07-14 02:26:31 +0000] [4595] [INFO] Worker exiting (pid: 4595)
[2020-07-14 02:26:31 +0000] [4592] [INFO] Shutting down: Master
[2020-07-14 02:26:31 +0000] [4592] [INFO] Reason: Worker failed to boot.
[2020-07-14 02:27:28 +0000] [4628] [INFO] Starting gunicorn 20.0.4
[2020-07-14 02:27:28 +0000] [4628] [INFO] Listening at: http://0.0.0.0:8000 (4628)
[2020-07-14 02:27:28 +0000] [4628] [INFO] Using worker: sync
[2020-07-14 02:27:28 +0000] [4631] [INFO] Booting worker with pid: 4631
[2020-07-14 02:27:28 +0000] [4631] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2020-07-14 02:27:28 +0000] [4631] [INFO] Worker exiting (pid: 4631)
[2020-07-14 02:27:28 +0000] [4628] [INFO] Shutting down: Master
[2020-07-14 02:27:28 +0000] [4628] [INFO] Reason: Worker failed to boot.
[2020-07-14 02:28:06 +0000] [4656] [INFO] Starting gunicorn 20.0.4
[2020-07-14 02:28:06 +0000] [4656] [INFO] Listening at: http://0.0.0.0:8000 (4656)
[2020-07-14 02:28:06 +0000] [4656] [INFO] Using worker: sync
[2020-07-14 02:28:06 +0000] [4663] [INFO] Booting worker with pid: 4663
[2020-07-14 02:28:06 +0000] [4663] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2020-07-14 02:28:06 +0000] [4663] [INFO] Worker exiting (pid: 4663)
[2020-07-14 02:28:06 +0000] [4664] [INFO] Booting worker with pid: 4664
[2020-07-14 02:28:06 +0000] [4664] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2020-07-14 02:28:06 +0000] [4664] [INFO] Worker exiting (pid: 4664)
[2020-07-14 02:28:06 +0000] [4656] [INFO] Shutting down: Master
[2020-07-14 02:28:06 +0000] [4656] [INFO] Reason: Worker failed to boot.
[2020-07-14 02:28:17 +0000] [4695] [INFO] Starting gunicorn 20.0.4
[2020-07-14 02:28:17 +0000] [4695] [INFO] Listening at: http://0.0.0.0:8000 (4695)
[2020-07-14 02:28:17 +0000] [4695] [INFO] Using worker: sync
[2020-07-14 02:28:17 +0000] [4702] [INFO] Booting worker with pid: 4702
[2020-07-14 02:28:17 +0000] [4702] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2020-07-14 02:28:17 +0000] [4702] [INFO] Worker exiting (pid: 4702)
[2020-07-14 02:28:17 +0000] [4695] [INFO] Shutting down: Master
[2020-07-14 02:28:17 +0000] [4695] [INFO] Reason: Worker failed to boot.
